### ISSUE TITLE
Setting up URL / Timeout without re-building the image

### ISSUE THREAD

**Issue by C00kiie** [holodeck-b2b/rest-backend#2]
From my basic understanding rest-backend sets up both the URL/Timeout by hard-coding it into the code, from a sysadmin/devops engineer perspective, it's a nightmare. Is it possible to set it up without compiling it?

**Comment by sfieten** [comment]
I'm not sure to which URL and timeout this applies, but you're right that the URL for receiving submissions indeed is fixed. This is needed because the URL path is used internally to determine how a request must be handled. 
For delivery of messages to the back-end the URL and time-out are however configurable in the P-Mode by adding the _URL_ and _TIMEOUT_ parameters to the delivery method.
